version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - cluster.name=suggestions-cluster
      - node.name=suggestions-node
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    # https://hub.docker.com/_/kibana
    image: kibana:7.17.13
    ports:
      - "5601:5601"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - elasticsearch
    container_name: suggestions_api
    volumes:
      - ./:/usr/src
    ports:
      - "8000:8000"

    stdin_open: true
    tty: true
